### ISSUE TITLE
Verificar por que uname -i devuelve unknown en los nodos. (Puede ser un problema al instalar Cuda)

### ISSUE THREAD

**Issue by ecolell** [gersolar/Ra#9]

**Comment by adrian-r** [comment]
Si es para ver la plataforma para instalar librerias, se puede usar uname
-m, que da como resultado, por ejemplo: x86_64

2015-05-07 18:48 GMT-03:00 Eloy Adonis Colell <notifications@github.com>:

**Comment by ecolell** [comment]
@adrian-r ok, pero la llamada a dicho commando no la realiza un script nuestro, es llamado por el instalador binario de CUDA.
